title: Cats, Bats and other assorted nouns
author: Cory Wyman
email: cwyman1@asu.edu
description: > # this means to ignore newlines until "baseurl:"
  This is your one stop site for looking at nouns that I list. It could be a rabbit,
  a lentil soup, aluminum. You name it. Or rather I do!

# social links
twitter_username: your-twitter-handle
github_username:  CoryStory

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal

